### ISSUE TITLE
expected path doesn't exist in repo .\csse_covid_19_data\csse_covid_19_daily_reports

### ISSUE THREAD

**Issue by AartBluestoke** [MelbourneDeveloper/COVID-19-DB#14]

**Comment by MelbourneDeveloper** [comment]
@AartBluestoke you need to clone the Johns Hopkins repo as per the instructions. 

I'm trying to decide whether to include the Johns Hopkins repo as a submodule or grab the files via the GitHub API. Both are possible.

**Comment by MelbourneDeveloper** [comment]
@AartBluestoke btw you can just download the database. It's not necessary to run the code. The link is on the front page.

**Comment by MelbourneDeveloper** [comment]
@AartBluestoke I have included the Johns Hopkins CSSE repo as a submodule so when you run the code it should be there by default. You need to make sure you initialize the submodule. There are instructions [here](https://github.com/MelbourneDeveloper/COVID-19-DB/blob/master/README.md#csv-reader). 

I also tried grabbing the data from the Github via the API. This is possible, but the problem is that GitHub limits unauthenticated requests to 60 per hour. That makes it impossible to download all the files unless the app forces the user to enter their Github credentials. Looking for a better way to deal with this...
